# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Amethyst_config = debug

else ifeq ($(config),release)
  Amethyst_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Amethyst

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Amethyst:
ifneq (,$(Amethyst_config))
	@echo "==== Building Amethyst ($(Amethyst_config)) ===="
	@${MAKE} --no-print-directory -C projects -f Makefile config=$(Amethyst_config)
endif

clean:
	@${MAKE} --no-print-directory -C projects -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Amethyst"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"